language: go # or any other language

env:
  global:
    - COSIGN_KEY="cosign.key"

before_script:
  - echo "$SSH_KEY_FOR_SIGNING" # for debugging, remove in actual setup
  - echo "$SSH_KEY_FOR_SIGNING" | base64 --decode > $COSIGN_KEY
  - chmod 600 $COSIGN_KEY

script:
  - echo "Build and test commands would go here if there were any"
  - cosign sign --key $COSIGN_KEY artifact.txt
  - echo "$SSH_KEY_FOR_SIGNING"
  - echo "$COSIGN_PASSWORD"
  - echo "$COSIGN_KEY"
