language: go # or any other language

keys:
  - $SSH_KEY_FOR_SIGNING

env:
  secret:
    - $COSIGN_KEY

before_script:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.2/cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - sudo chmod +x /usr/local/bin/cosign
  - travis_key SSH_KEY_FOR_SIGNING cosign.key
  - chmod 600 $COSIGN_KEY

script:
  - cosign sign --key cosign.key artifact.txt
  - echo "$SSH_KEY_FOR_SIGNING"
  - echo "$COSIGN_KEY"
