language: generic

env:
  global:
    - COSIGN_PASSWORD=$COSIGN_PASSWORD

before_script:
  - openssl aes-256-cbc -K $SSH_KEY_FOR_SIGNING -iv $SSH_KEY_FOR_SIGNING -in ssh_key.enc -out ssh_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ssh_key
  - ssh-add ssh_key

script:
  - cosign sign --key ssh_key artifact.txt
  - echo $COSIGN_PASSWORD
  - echo $SSH_KEY_FOR_SIGNING
