language: generic

# Define the environment variable that holds the key
env:
  global:
    - SIGNING_KEY=$SSH_KEY_FOR_SIGNING

# Specify the build matrix
jobs:
  include:
    - stage: test
      script:
        - echo "Running tests..."
        # Add your test commands here
        - ./run-tests.sh
    
    - stage: sign
      script:
        - echo "Signing software..."
        # Use the signing key to sign your software
        - echo $SIGNING_KEY | base64 --decode > signing_key.asc
        - gpg --import signing_key.asc
        - gpg --batch --yes --passphrase=$SIGNING_KEY_PASSPHRASE --output signed-file --sign original-file
